# Generated by Django 4.0.3 on 2022-04-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searchtagsmodel',
        ),
    ]
