# Generated by Django 4.0.3 on 2022-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=6)),
                ('imageName', models.CharField(max_length=35)),
                ('imageID', models.IntegerField()),
                ('testfield', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BioAndInterests',
        ),
    ]
