# Generated by Django 4.0.3 on 2022-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_profiles_delete_bioandinterests'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePicCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
