# Generated by Django 4.0.3 on 2022-04-11 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0003_profilepiccounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profilepage/images/'),
            preserve_default=False,
        ),
    ]
