# Generated by Django 4.0.3 on 2022-04-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_profiles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imageFile', models.ImageField(upload_to='djangoImages/')),
            ],
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
