# Generated by Django 4.0.3 on 2022-04-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingCrationModel',
            new_name='ListingCreationModel',
        ),
    ]
