# Generated by Django 4.0.3 on 2022-04-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0005_alter_listingcreationmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
