# Generated by Django 4.0.3 on 2022-05-02 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCreationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('eventdate', models.CharField(default='4/11/2022', max_length=10)),
                ('outdoors', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('recreation', models.BooleanField()),
                ('learning', models.BooleanField()),
                ('author', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
