# Generated by Django 2.0.13 on 2022-04-12 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingCreationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='anonymous', max_length=200)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('eventdate', models.CharField(default='4/11/2022', max_length=10)),
                ('outdoors', models.BooleanField()),
                ('sports', models.BooleanField()),
                ('recreation', models.BooleanField()),
                ('learning', models.BooleanField()),
            ],
        ),
    ]
