# Generated by Django 4.0.3 on 2022-05-01 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listingcreation', '0002_alter_listingcreationmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
