# Generated by Django 4.0.3 on 2022-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0002_listingcreationmodel_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcreationmodel',
            name='recurperiod',
            field=models.CharField(default='Never', max_length=20),
        ),
        migrations.AddField(
            model_name='listingcreationmodel',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
