# Generated by Django 4.0.3 on 2022-04-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0002_rename_listingcrationmodel_listingcreationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='learning',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='outdoors',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='recreation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='sports',
            field=models.BooleanField(),
        ),
    ]
