# Generated by Django 4.0.3 on 2022-04-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0003_alter_listingcreationmodel_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
