# Generated by Django 4.0.3 on 2022-05-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0003_listingcreationmodel_recurperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='recurperiod',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
