# Generated by Django 4.0.3 on 2022-04-11 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0004_alter_listingcreationmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
