# Generated by Django 4.0.3 on 2022-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0005_remove_listingcreationmodel_recurperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='eventdate',
            field=models.CharField(default='12/24/2024', max_length=10),
        ),
    ]
