# Generated by Django 4.0.3 on 2022-04-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0006_alter_listingcreationmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcreationmodel',
            name='author',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
