# Generated by Django 4.0.3 on 2022-04-11 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0007_listingcreationmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcreationmodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
