# Generated by Django 4.0.3 on 2022-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0008_listingcreationmodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingcreationmodel',
            name='eventday',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '4'), ('5', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='listingcreationmodel',
            name='eventmonth',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '4'), ('5', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='listingcreationmodel',
            name='eventyear',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2022', max_length=4),
        ),
    ]
