# Generated by Django 4.0.3 on 2022-04-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0009_listingcreationmodel_eventday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='eventday',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='eventmonth',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='listingcreationmodel',
            name='eventyear',
            field=models.IntegerField(default='2022'),
        ),
    ]
