# Generated by Django 4.0.3 on 2022-04-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingcreation', '0010_alter_listingcreationmodel_eventday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcreationmodel',
            name='eventday',
        ),
        migrations.RemoveField(
            model_name='listingcreationmodel',
            name='eventmonth',
        ),
        migrations.RemoveField(
            model_name='listingcreationmodel',
            name='eventyear',
        ),
        migrations.AddField(
            model_name='listingcreationmodel',
            name='eventdate',
            field=models.CharField(default='4/11/2022', max_length=10),
        ),
    ]
