# Generated by Django 2.0.13 on 2022-04-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='biography',
        ),
    ]
