# Generated by Django 2.0.13 on 2022-04-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20220424_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
    ]
