// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Listing Creation', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('post_event_logged_in', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.linkText("Login/Register")).click()
    await driver.findElement(By.id("id_username")).sendKeys("seleniumautomated")
    await driver.findElement(By.id("id_password")).sendKeys("ThisIsASecret1")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.id("id_title")).click()
    await driver.findElement(By.id("id_title")).sendKeys("Basketball Tournament")
    await driver.findElement(By.id("id_description")).click()
    await driver.findElement(By.id("id_description")).sendKeys("University at Buffalo is hosting a annual basketball tournament this coming week! RSVP today to meet new people and hang out! Come alone or come with a premade team!")
    await driver.findElement(By.id("id_eventday")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventday"))
      await dropdown.findElement(By.xpath("//option[. = '5']")).click()
    }
    await driver.findElement(By.css("#id_eventday > option:nth-child(5)")).click()
    await driver.findElement(By.id("id_eventmonth")).click()
    await driver.findElement(By.id("id_eventday")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventday"))
      await dropdown.findElement(By.xpath("//option[. = '21']")).click()
    }
    await driver.findElement(By.css("option:nth-child(21)")).click()
    await driver.findElement(By.id("id_eventmonth")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventmonth"))
      await dropdown.findElement(By.xpath("//option[. = '5']")).click()
    }
    await driver.findElement(By.css("#id_eventmonth > option:nth-child(5)")).click()
    await driver.findElement(By.id("id_eventyear")).click()
    await driver.findElement(By.css("#id_eventyear > option:nth-child(1)")).click()
    await driver.findElement(By.id("id_recurring")).click()
    await driver.findElement(By.css("#id_recurring > option:nth-child(1)")).click()
    await driver.findElement(By.id("id_sports")).click()
    await driver.findElement(By.css("input:nth-child(11)")).click()
    {
      const elements = await driver.findElements(By.xpath("//h1[contains(.,\'Basketball Tournament\')]"))
      assert(elements.length)
    }
  })
  it('post_event_not_logged_in', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1283, height: 814 })
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.xpath("//h1[contains(.,\'Please log in to create a post\')]"))
      assert(elements.length)
    }
  })
  it('filtering_events_by_tag_multiple', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1283, height: 814 })
    await driver.findElement(By.id("id_sports")).click()
    await driver.findElement(By.id("id_learning")).click()
    await driver.findElement(By.xpath("//input[@value=\'Filter\']")).click()
    {
      const elements = await driver.findElements(By.xpath("//h1[contains(.,\'Basketball Tournament\')]"))
      assert(!elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//p[contains(.,\'Tags: Sports\')]"))
      assert(!elements.length)
    }
  })
  it('filtering_events_by_tag', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1283, height: 814 })
    await driver.findElement(By.id("id_sports")).click()
    await driver.findElement(By.xpath("//input[@value=\'Filter\']")).click()
    {
      const elements = await driver.findElements(By.xpath("//h1[contains(.,\'Basketball Tournament\')]"))
      assert(elements.length)
    }
    {
      const elements = await driver.findElements(By.xpath("//p[contains(.,\'Tags: Sports\')]"))
      assert(elements.length)
    }
  })
})
