// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Reset for demo', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('reset_for_demo', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/login/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.id("id_username")).click()
    await driver.findElement(By.id("id_username")).sendKeys("seleniumautomated")
    await driver.findElement(By.id("id_password")).sendKeys("ThisIsASecret1")
    await driver.findElement(By.xpath("//button[@type=\'submit\']")).click()
    vars["x"] = await driver.getTitle()
    if (!!await driver.executeScript("return (arguments[0] == \"Login Page\")", vars["x"])) {
      console.log(vars["x"])
    } else {
      console.log(vars["x"])
      {
        const elements = await driver.findElements(By.linkText("Delete Account"))
        assert(elements.length)
      }
      await driver.findElement(By.xpath("//a[contains(@href, \'/profile/delete_account\')]")).click()
      await driver.findElement(By.xpath("//button[@name=\'delete\']")).click()
    }
    await driver.close()
  })
})
