// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('RSVP', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('rsvp_logged_in', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.css(".container-listing:nth-child(1) .btn")).click()
    await driver.findElement(By.linkText("log in")).click()
    await driver.findElement(By.id("id_username")).sendKeys("seleniumautomated")
    await driver.findElement(By.id("id_password")).sendKeys("ThisIsASecret1")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.xpath("(//input[@value=\'RSVP\'])[2]")).click()
    await driver.get("https://www.google.com/")
    await driver.findElement(By.linkText("Sign in")).click()
    await driver.findElement(By.id("identifierId")).click()
    await driver.findElement(By.id("identifierId")).sendKeys("unemployedbumstest@gmail.com")
    await driver.findElement(By.id("identifierId")).sendKeys(Key.ENTER)
    await driver.findElement(By.name("password")).sendKeys("ThisIsASecret1")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Gmail")).click()
    {
      const elements = await driver.findElements(By.xpath("(//span[@name=\'EVNT RSVP\'])[2]"))
      assert(elements.length)
    }
  })
  it('rsvp_not_logged_in', async function() {
    await driver.get("http://www-student.cse.buffalo.edu:8051/home/")
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    await driver.findElement(By.css(".container-listing:nth-child(1) .btn")).click()
  })
})
